const fs = require('fs');
let content = fs.readFileSync('src/App.tsx', 'utf8');
const lines = content.split('\n');

for (let i = 1530; i < 1550; i++) {
    // There are NO commas in RU block from `testiText7` onwards!
    // Why? The regex replacement must have stripped the commas.
    // Let's fix this specific block and see if there are other such blocks.
    if (!lines[i].endsWith(',') && !lines[i].endsWith('{') && !lines[i].endsWith('}')) {
        // console.log(`${i+1}: ${lines[i]}`);
    }
}
// Let's just fix all missing commas at the end of properties within the TRANSLATIONS object.
// A property usually ends with `",` or `</>,`

content = content.replace(/(testiText[0-9]: "[^"]*")(\n)/g, '$1,$2');
content = content.replace(/(testiAuthor[0-9]: "[^"]*")(\n)/g, '$1,$2');
content = content.replace(/(heroProblemTitle: "[^"]*")(\n)/g, '$1,$2');
content = content.replace(/(heroProblemDesc: <><p>.*?<\/p><\/>)(\n)/g, '$1,$2');
content = content.replace(/(heroSolutionTitle: "[^"]*")(\n)/g, '$1,$2');
content = content.replace(/(heroSolutionDesc: <><p>.*?<\/p><\/>)(\n)/g, '$1,$2');
content = content.replace(/(heroWhoTitle: "[^"]*")(\n)/g, '$1,$2');
content = content.replace(/(heroWhoDesc: <><p>.*?<\/p><\/>)(\n)/g, '$1,$2');
content = content.replace(/(heroWhyTitle: "[^"]*")(\n)/g, '$1,$2');
content = content.replace(/(heroWhyDesc: <><p>.*?<\/p><\/>)(\n)/g, '$1,$2');
content = content.replace(/(heroDisclaimerTitle: "[^"]*")(\n)/g, '$1,$2');
content = content.replace(/(heroDisclaimerDesc: <><p>.*?<\/p><\/>)(\n)/g, '$1,$2');
content = content.replace(/(followupPlaceholder: "[^"]*")(\n)/g, '$1,$2');
content = content.replace(/(termsContent: <>.*?<\/>)(\n)/g, '$1,$2');
content = content.replace(/(privacyContent: <>.*?<\/>)(\n)/g, '$1,$2');
content = content.replace(/(imprintContent: <>.*?<\/>)(\n)/g, '$1,$2');
content = content.replace(/(underConstructionBtn: "[^"]*")(\n)/g, '$1,$2');
content = content.replace(/(guestLoginBtn: "[^"]*")(\n)/g, '$1,$2');
content = content.replace(/(underConstructionTitle: "[^"]*")(\n)/g, '$1,$2');
content = content.replace(/(underConstructionDesc1: "[^"]*")(\n)/g, '$1,$2');
content = content.replace(/(underConstructionDesc2: "[^"]*")(\n)/g, '$1,$2');
content = content.replace(/(password: "[^"]*")(\n)/g, '$1,$2');
content = content.replace(/(loginBtn: "[^"]*")(\n)/g, '$1,$2');
content = content.replace(/(incorrectPassword: "[^"]*")(\n)/g, '$1,$2');
content = content.replace(/(showTip: "[^"]*")(\n)/g, '$1,$2');
content = content.replace(/(hideTip: "[^"]*")(\n)/g, '$1,$2');
content = content.replace(/(guestTip: "[^"]*")(\n)/g, '$1,$2');
content = content.replace(/(iAcceptThe: "[^"]*")(\n)/g, '$1,$2');
content = content.replace(/(and: "[^"]*")(\n)/g, '$1,$2');
content = content.replace(/(fillMandatory: "[^"]*")(\n)/g, '$1,$2');

// Fix duplicates generated by the above (e.g. `",,` or `</>,,`)
content = content.replace(/,\n/g, ',\n');
content = content.replace(/,,/g, ',');

fs.writeFileSync('src/App.tsx', content);

